### ISSUE TITLE
Help ? 

### ISSUE THREAD

**Issue by Juininho2k21** [Ramys/Ramys#1]
how do i talk to you?do you have Whatsapp? email?

**Comment by Ramys** [comment]
Fala maninho, eu não cheguei a instalar o projeto.
https://github.com/Vulcanwebmaster/apostas-esportivas
eu só trunquei...irei testar aqui e volto a falar com vc ..
@Juininho2k21

**Comment by Juininho2k21** [comment]
Tamo junto irmão @Ramys

**Comment by Juininho2k21** [comment]
Estou te aguardando tenho um $ do café pra vc. Kk Tmj @Ramys

**Comment by Ramys** [comment]
Vc testou em qual máquina?

**Comment by Juininho2k21** [comment]
Linux @Ramys 
https://servidoraton9.com.br/jr/jresportes

**Comment by Juininho2k21** [comment]
Me chama no WhatsApp +55 81 982349819 @Ramys
